# ==========================================
# NOMBRE DE LA APLICACIÓN Y PUERTO
# ==========================================
spring.application.name=fitelyback-api
server.port=8080

# ==========================================
# CONEXIÓN A LA BASE DE DATOS (SUPABASE - POSTGRESQL)
# ==========================================
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.tiukbsomkfrlewxycfdb
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ==========================================
# 'update' creará las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# No mantener la conexión a la base abierta durante toda la petición
spring.jpa.open-in-view=false

# ==========================================
# SEGURIDAD (JWT)
# ==========================================
# Clave de 256 bits en Base64, leída de variable de entorno
jwt.secret=${JWT_SECRET}
# Expiración del token: 24 horas en milisegundos
jwt.expiration=86400000